### ISSUE TITLE
Mapping inventory should be lower-case if mapping is case insensitive

### ISSUE THREAD

**Issue by roedoejet** [ReadAlongs/Studio#40]
Currently there is at least one method (maybe more, this needs checking) which doesn't apply lower-casing to the mapping inventory. 

Take the following at the beginning of `is_word_character` in `readalongs/text/tokenize_xml.py`:

```python
  def is_word_character(self, c):
        if not self.case_sensitive:
            c = c.lower()
        if c in self.inventory:
            return True
```

The inventory hasn't been lower-cased yet and this method doesn't do what's expected (ie return True if the inventory has upper-case characters).

**Comment by joanise** [comment]
I believe this is not a bug, because this line is intended to capture non-letter character in `self.inventory`. This block a few lines below catches all letters in all scripts:
```
        if get_unicode_category(c) in ["letter", "number", "diacritic"]:
            return True
```
Note: this code now lives in `g2p/mappings/tokenizer.py` but persists as is.

But I agree, it would be tidier and probably more robust to lowercase the inventory as well when the tokenizer object is created.
`Tokenizer.__init__()` and `MultiHopTokenizer.__init__()` should both add logic to lowercase `self.inventory` when `self.case_sensitive` is set to `False`.

In fact, multi-character inputs could cause trouble: add rule `A-B` -> `c-d` to a case-insensitive language with no other rules containing hyphens in the input. In this case, the word `AAA-BBB` is likely to get tokenized to [word `AAA`, non-word `-`, word `BBB`] instead of staying as just one word.

However, this is unlikely to be a problem, because a writer of a case-insensitive mapping would naturally write that rule `a-b` -> `c-d`. But again, it would make sense to actually unit test the case I'm describing here and fix the code for it.
